In [3]:
import numpy as np
import tensorflow as tf
from keras import Sequential

# KNN coursework

In [19]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

# 创建布尔索引
pos = Y_train == 1 
neg = Y_train == 0

X_train[pos]

array([3., 4., 5.], dtype=float32)

In [20]:
'''
第一个参数 (1): 这是该层的单元（或神经元）数量。在这个例子中，1 表示该层只有一个神经元。
input_dim=1: 这个参数指定输入数据的维度。在这个例子中，input_dim=1 表示每个输入样本是一维的。这通常用于模型的第一层，以告诉模型输入数据的形状。
activation='sigmoid': 这个参数定义了激活函数，用于决定神经元的输出。'sigmoid' 是一种常用的激活函数，它将输入值映射到 (0, 1) 范围内，常用于二元分类问题的输出层。
name='L1': 这个参数为层提供了一个名称。在这个例子中，层被命名为 'L1'。这对于在后续处理中引用或调试特定层非常有用。
'''
model = Sequential(
    [
        tf.keras.layers.Dense(1, input_dim=1,  activation = 'sigmoid', name='L1')
    ]
)

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
logistic_layer = model.get_layer("L1")
w, b = logistic_layer.get_weights()
print(w, b)

[[-0.95140016]] [0.]


In [22]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
# 设置w，b
logistic_layer.set_weights([set_w, set_b])

In [23]:
a1 = model.predict(X_train[0].reshape(1, 1))

1/1 [==============================] - 0s 52ms/step


2023-11-13 14:56:08.207881: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


In [1]:
print(a1)

NameError: name 'a1' is not defined

In [10]:
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / e_x.sum(axis=1, keepdims=True)

x = np.array([[1, 2, 3, 6],
              [2, 4, 5, 6],
              [1, 2, 3, 6]])

print(softmax(x))

[[0.00626879 0.01704033 0.04632042 0.93037047]
 [0.01203764 0.08894682 0.24178252 0.65723302]
 [0.00626879 0.01704033 0.04632042 0.93037047]]
